### ISSUE TITLE
 latest mm fails to start with MMM-Djoke enabled

### ISSUE THREAD

**Issue by ihadx** [cowboysdude/MMM-Djoke#1]
mm starts ok when MMM-Djoke is disabled
Any ideas on things to try?

**Comment by ihadx** [comment]
This issue still exists. Any ideas? Here is the relevent section of the log file:
[27.02.2022 10:39.31.482] [ERROR] App threw an error during load
[27.02.2022 10:39.31.485] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Djoke/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Djoke/node_helper.js:8:17)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
[27.02.2022 10:39.31.487] [ERROR] Whoops! There was an uncaught exception...
[27.02.2022 10:39.31.493] [ERROR] Error: Cannot find module 'request'
